# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58a5eadea72bfe010393522b1d50f1e83ded9fe7d13595714008f95d638030274c4f69018e1b780c8f4df972f4c9c60c8450e7ccab2c5e63630d73fe295965ef

test:
  secret_key_base: ace6aca9d96bff91721c789a583ed000801baba633b85c37987a8b0940858f1dabc349ab4fa18bad6b664759f8673c970a863a2b56060572180cb6ab015e6156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
